# Generated by Django 4.2.10 on 2025-12-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_prediction_category_prediction_final_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='predictor_t_name_f3f676_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['league'], name='predictor_t_league__b8fd01_idx'),
        ),
        migrations.AddIndex(
            model_name='league',
            index=models.Index(fields=['category'], name='predictor_l_categor_080c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='league',
            index=models.Index(fields=['name'], name='predictor_l_name_854469_idx'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='predictor.league'),
        ),
    ]
