# Generated by Django 4.2.10 on 2025-12-29 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0005_prediction_archived_date_prediction_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('total_predictions', models.IntegerField(db_index=True, default=0)),
                ('unique_teams_count', models.IntegerField(default=0)),
                ('unique_leagues_count', models.IntegerField(default=0)),
                ('first_prediction_date', models.DateTimeField(blank=True, null=True)),
                ('last_prediction_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user', 'session_key', 'prediction_date'], name='predictor_p_user_id_27aa1b_idx'),
        ),
        migrations.AddField(
            model_name='billingusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='billingusage',
            index=models.Index(fields=['user', 'is_active', '-last_updated'], name='predictor_b_user_id_78d0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='billingusage',
            index=models.Index(fields=['session_key', 'is_active', '-last_updated'], name='predictor_b_session_3764fd_idx'),
        ),
        migrations.AddIndex(
            model_name='billingusage',
            index=models.Index(fields=['is_active', '-last_updated'], name='predictor_b_is_acti_e9d915_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billingusage',
            unique_together={('user', 'session_key')},
        ),
    ]
