# Generated by Django 4.2.7 on 2026-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_prevent_duplicate_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('standard', 'Standard Plan'), ('starter', 'Starter Plan'), ('vip', 'VIP Plan')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='KSH', max_length=3),
        ),
    ]
