# Generated by Django 4.2.7 on 2026-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_prevent_duplicate_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='free_matches_limit',
            field=models.IntegerField(default=1),
        ),
    ]
