# Generated by Django 4.2.7 on 2026-01-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_subscription_plan_type_alter_subscription_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='free_matches_limit',
            field=models.IntegerField(default=1),
        ),
    ]
