# Generated by Django 4.2.7 on 2026-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_alter_userprofile_free_matches_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
