# Generated by Django 4.2.7 on 2026-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_alter_userprofile_free_matches_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='matches_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='matches_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
