# Generated by Django 4.2.7 on 2026-01-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_alter_userprofile_free_matches_limit'),
        ('predictor', '0011_subscription_plan_type'),
    ]

    operations = [
    ]
