# Generated by Django 4.2.7 on 2026-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_subscription_matches_limit_subscription_matches_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
